---
# tasks file for apache2_debian



- name: Install apache2
  apt:
    name: apache2
    state: present
    update_cache: yes
    
#- name: Check if there is a default index.html file
#  stat: 
#    path: /var/www/html/index.html
#  register: index_file
#
#- name: Create a backup file for default index.html file
#  command: "mv /var/www/html/index.html /var/www/html/index.html.bak"
#  when: index_file.stat.exists

- name: Copy from config_files/index.html to /var/www/html/index.html
  copy:
    src: config_files/index.html
    dest: /var/www/html/index.html
    backup: yes

- name: Create folder named combo_debian.com
  file:
    path: /var/www/html/combo_debian.com
    state: directory
    owner: combo
    group: combo
    mode: '0755'
  register: create_host

- name: Copy from config_files/index_debian.html to /var/www/html/combo_debian.com/index.html
  copy:
    src: config_files/index_debian.html
    dest: /var/www/html/combo_debian.com/index.html

- name: Copy from config_files/combo_debian.com.conf to /etc/apache2/sites-available/combo_debian.com.conf
  copy:
    src: config_files/combo_debian.com.conf
    dest: /etc/apache2/sites-available/combo_debian.com.conf

- name: Enable the Apache2 combo_debian.com and disable 000-default.conf
  shell: "a2ensite combo_debian.com && a2dissite 000-default.conf"
  when: create_host.changed

- name: Start Apache2 service
  systemd:
    name: apache2
    state: started
    enabled: yes
