---
# tasks file for install-docker-debian



- name: Install apt-transport-https ca-certificates curl software-properties-common
  apt:
    name:
      - apt-transport-https 
      - ca-certificates
      - curl 
      - software-properties-common
    state: present
    update_cache: yes

- name: Adding Dockers GPG Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Installing the Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" 
    state: present
    update_cache: yes

- name: Installing the Latest Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Create the docker group
  group:
    name: docker
    state: present

- name: Add docker group to my user
  user:
    name: combo
    group: docker

- name: Install python3 and python3-pip
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install docker-py using pip
  pip:
    name: docker-py
    state: forcereinstall
    
- name: Start and Enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes
